name: mendable Workflow

on:
  push:
    branches:
      - master

  pull_request:
    branches:     
      - master

jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4         
      with:
        python-version: "3.9.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/firecrawl_pydantic:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/firecrawl_pydantic:latest
      #always write the container name in the run command
    - name: Run Docker container with increased memory
      run: |
        docker run --name beautiful_cray -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/firecrawl_pydantic:latest

    - name: Cleanup Docker container
      run: |
        docker stop beautiful_cray
        docker rm beautiful_cray

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3    
      with:
        name: test-results
        path: .pytest_cache/
